### ISSUE TITLE
last two forms in views/index.html have same id 

### ISSUE THREAD

**Issue by DaniloNovakovic** [freeCodeCamp/boilerplate-project-issuetracker#2]
I have noticed that there are 2 forms with same id (`testForm2`)  in index.html which makes last form submit `put` request instead of `delete`

_Bonus issue:_ 
jQuery script doesn't have an error callback, which in my opinion should since it is logical to set res.status to 400 on bad request (ex. if invalid _id was sent), and it is required in user stories to send adequate error messages so why not display them?
Solution for this could be to add `error: function (data) {$('#jsonResult').text(data.responseText); }` to`ajax` call

**Comment by dineshigdd** [comment]
yes, I noticed it too. it should be id = "testForm3"

**Comment by scissorsneedfoodtoo** [comment]
Closed by https://github.com/freeCodeCamp/boilerplate-project-issuetracker/pull/1
